apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-go
  labels:
    app: test-app-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-go
  template:
    metadata:
      labels:
        app: test-app-go
    spec:
      containers:
      - name: test-app-go
        # Какой-то левый образ
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898

---

apiVersion: v1
kind: Service
metadata:
  name: test-app-go-svc
  labels:
    app: test-app-go
spec:
  selector:
    app: test-app-go
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9898
    targetPort: 9898 