version: '3.8'

services:
  db1:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: chatops
    ports:
      - "5433:5432"
    volumes:
      - db1data:/var/lib/postgresql/data


volumes:
  db1data:
