name: Deploy app to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/chatops
            git pull origin main

            echo "Init db variables..."
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_NAME=${{ secrets.POSTGRES_NAME }}" >> .env

            echo "Init app variables..."
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            echo "GPT_KEY=${{ secrets.GPT_KEY }}" >> .env
            echo "GPT_CATALOG=${{ secrets.GPT_CATALOG }}" >> .env
            echo "PROMETHEUS_URL=${{ secrets.PROMETHEUS_URL }}" >> .env
            echo "ALERTMANAGER_URL=${{ secrets.ALERTMANAGER_URL }}" >> .env
            
            echo "Init kuber config..."
            echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ./kubeconfig
          
            docker compose up -d --build
